from defined_srt import SubtitleItem, write_srt_to_file
# 使用示例
if __name__ == "__main__":
    # 创建SubtitleItem实例列表
    demo_subtitles = [
        SubtitleItem(timeMinute=1, timeSecond=36.21, text="贝多芬的《第三钢琴协奏曲》是他首次（也是唯一一次）以小调创作的协奏曲。弦乐部分以一段简洁而动人的主题齐奏开场，深沉而强烈，随后木管乐器呼应了这一主题。"),
        SubtitleItem(timeMinute=2, timeSecond=5.14, text="弦乐此时显得更加犹豫，更具疑问性；木管乐器则以直白的回应作答。接着，乐团进发出活力，将开篇主题以大调重新演绎。"),
        SubtitleItem(timeMinute=2, timeSecond=47.20, text="在短暂的张力上升后，乐团的音乐来回滚动，却未给出明确的解决。 随后，单簧管和巴松管轻柔地引入了一个新的、如歌般的主题。"),
        SubtitleItem(timeMinute=3, timeSecond=26.23, text="现在，新主题在第一长笛的高音区浮现，小提琴和其他木管乐器紧随其后，随后主题转向更为阴暗的色彩。注意听小提琴演奏的快速重复音，即“颤音”。"),
        SubtitleItem(timeMinute=3, timeSecond=51.15, text="开篇主题再次回归。每当一组乐器开始演奏时，另一组乐器便会将其打断：先是巴松管，接着是第一小提琴，最后是整个木管乐组。"),
        SubtitleItem(timeMinute=4, timeSecond=19.08, text="音乐似乎平静下来，随后又一次进发，最后重复开篇主题。弦乐在木管乐器之后几秒呼应主题，最终以三个力度十足的和弦结束。"),
        SubtitleItem(timeMinute=5, timeSecond=1.26, text="钢琴的首次进入完全符合人们对浪漫主义者贝多芬的普遍印象：一位桀骜的创作者，擅长谱写极具表现力、情感激荡澎湃的音乐。"),
        SubtitleItem(timeMinute=5, timeSecond=38.03, text="注意乐团每个简短的乐句如何被钢琴越来越“半音化”（使用作品主调之外的多彩音符）的回应所接应，之后逐渐溶解一段柔和的新旋律。"),
        SubtitleItem(timeMinute=6, timeSecond=20.22, text="聆听圆号持续奏出轻柔的长音。这被称为“踏板音”，类似于管风琴手用脚在踏板上保持的长音。"),
        SubtitleItem(timeMinute=6, timeSecond=38.18, text="钢琴部分轻松自如地过渡到乐章的抒情第二主题，在极简伴奏下演奏，之后将其传递给弦乐部分。"),
        SubtitleItem(timeMinute=7, timeSecond=27.15, text="独奏钢琴以四个赞美诗般的和弦进入，这是对前一主题简化并放慢的变奏。"),
        SubtitleItem(timeMinute=7, timeSecond=54.04, text="注意听，音乐逐渐显得更具驱动力。弦乐和圆号的“短一长”重复模式以及钢琴的飞速音阶进一步增强了这种效果。"),
        SubtitleItem(timeMinute=8, timeSecond=8.13, text="在键盘上广泛游走后，钢琴聚焦于一个长而高的颤音（快速交替演奏两个音符），随后向上移动，最终又下坠融入一段完整的乐团乐段。"),
        SubtitleItem(timeMinute=8, timeSecond=50.02, text="注意听节奏能量的突然变化，以及现在落在每小节第二拍上的“突强”重音。"),
        SubtitleItem(timeMinute=9, timeSecond=12.09, text="钢琴轰鸣着进入，连续演奏三个上升音阶，最后是一个号角齐奏般的动机。乐团回应时，暗示了一种疑虑，情绪也随之转变。"),
        SubtitleItem(timeMinute=9, timeSecond=31.08, text="在这一部分，钢琴家的右手以八度演奏主旋律，左手紧随其后。独奏旋律线流畅滑行，而 乐团围绕着它创造出饶有趣味的节奏。"),
        SubtitleItem(timeMinute=9, timeSecond=44.04, text="木管组与钢琴之间有一段简短的对话，各自重复其陈述，随后钢琴音符变得如闪电般迅捷，轻盈地在键盘上上下穿梭。"),
        SubtitleItem(timeMinute=10, timeSecond=58.28, text="乐团以全力齐奏重复不祥的主部主题，回应钢琴活泼、迅捷的经过段。这种热烈的能量很快消散，钢琴带出了更为柔和的情绪。"),
        SubtitleItem(timeMinute=11, timeSecond=37.20, text="或许你能听出钢琴奏出相同的极快音符（每拍四个音），而木管和弦乐则演奏两条对比鲜明的较慢旋律。"),
        SubtitleItem(timeMinute=11, timeSecond=54.24, text="钢琴与乐团刚刚分享了乐章如歌的第二主题；随后，钢琴进行了片刻独奏，哀怨的双簧管和巴松管给出回应。"),
        SubtitleItem(timeMinute=12, timeSecond=38.21, text="现在，钢琴展开了一段更长的独奏。弦乐提谨慎地伴奏，主要使用单和弦，帮助强化每小节的主拍。"),
        SubtitleItem(timeMinute=13, timeSecond=1.26, text="独奏家的左手手指变得更加活跃，上下奔跑，而右手在高音区演奏装饰音；随后，两只手再次以八度结合，向前推进。"),
        SubtitleItem(timeMinute=13, timeSecond=33.08, text="钢琴再次奏响一个长而高的颤音，同时圆号和小号演奏坚实的主旋律，推动乐团进入一阵狂热，随后突然停止。"),
        SubtitleItem(timeMinute=14, timeSecond=12.16, text="钢琴开始了一段华彩乐段，在这种篇幅较长、形式自由的无伴奏乐段里，独奏者得以充分展示其技巧。华彩乐段通常是即兴的，但贝多芬为这段华彩谱写了完整的音乐。"),
        SubtitleItem(timeMinute=14, timeSecond=36.22, text="典型的华彩乐段会融入并发展已出现过的素材和主题。在这里，贝多芬以多个主题为基础，进发出狂野的音符洪流。"),
        SubtitleItem(timeMinute=15, timeSecond=1.14, text="在使用“两个长和弦后接快速短音”的模式四次后，贝多芬将这一乐思带入了他悸动想象的深处。"),
        SubtitleItem(timeMinute=15, timeSecond=31.15, text="这里近乎直接引用了乐章早前部分，其简洁与我们刚刚耳闻的狂热形成了鲜明对比。"),
        SubtitleItem(timeMinute=15, timeSecond=59.24, text="贝多芬瞬间改变了情绪：与华彩乐段通常的写法不同，这里的音乐标记为“急板”（非常快），释放出一个全新的乐思。"),
        SubtitleItem(timeMinute=16, timeSecond=30.16, text="正如他之前所做的那样，贝多芬让钢琴的右手奏出一个长颤音，但现在左手也随之加入，演奏与右手非常接近的音。"),
        SubtitleItem(timeMinute=16, timeSecond=57.11, text="又出现了一串颤音。这些颤音以几乎难以察觉的变化，向乐团发出了华彩乐段即将结束的信号。"),
        SubtitleItem(timeMinute=17, timeSecond=9.02, text="沉寂的乐团幽灵般地回归。定音鼓将一个安静而不祥的音型重复四次，助推乐团的张力迅速攀升。"),
        SubtitleItem(timeMinute=17, timeSecond=50.26, text="在最后的华丽段落中，整个乐团轰鸣，钢琴疾驰而下，随后再次窜升；整个乐团以节奏一致的四个清脆和弦结束。"),
        SubtitleItem(timeMinute=18, timeSecond=11.25, text="    "),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
        # SubtitleItem(timeMinute=0000, timeSecond=0000, text="___"),
    ]

    try:
        write_srt_to_file("./output/贝钢协3+英雄生涯@4020+尼尔森斯+布朗夫曼.srt", demo_subtitles)
    except Exception as e:
        print(f"程序运行出错: {str(e)}")

        