from defined_srt import SubtitleItem, write_srt_to_file
# 使用示例
if __name__ == "__main__":
    # 创建SubtitleItem实例列表
    demo_subtitles = [
        SubtitleItem(timeMinute=1, timeSecond=36.21, text="贝多芬的《第三钢琴协奏曲》是他首次（也是唯一一次）以小调创作的协奏曲。弦乐部分以一段简洁而动人的主题齐奏开场，深沉而强烈，随后木管乐器呼应了这一主题。"),
        SubtitleItem(timeMinute=2, timeSecond=5.14, text="弦乐此时显得更加犹豫，更具疑问性；木管乐器则以直白的回应作答。接着，乐团进发出活力，将开篇主题以大调重新演绎。"),
        SubtitleItem(timeMinute=2, timeSecond=47.20, text="在短暂的张力上升后，乐团的音乐来回滚动，却未给出明确的解决。 随后，单簧管和巴松管轻柔地引入了一个新的、如歌般的主题。"),
        SubtitleItem(timeMinute=3, timeSecond=26.23, text="现在，新主题在第一长笛的高音区浮现，小提琴和其他木管乐器紧随其后，随后主题转向更为阴暗的色彩。注意听小提琴演奏的快速重复音，即“颤音”。"),
        SubtitleItem(timeMinute=3, timeSecond=51.15, text="开篇主题再次回归。每当一组乐器开始演奏时，另一组乐器便会将其打断：先是巴松管，接着是第一小提琴，最后是整个木管乐组。"),
        SubtitleItem(timeMinute=4, timeSecond=19.08, text="音乐似乎平静下来，随后又一次进发，最后重复开篇主题。弦乐在木管乐器之后几秒呼应主题，最终以三个力度十足的和弦结束。"),
        SubtitleItem(timeMinute=5, timeSecond=1.26, text="钢琴的首次进入完全符合人们对浪漫主义者贝多芬的普遍印象：一位桀骜的创作者，擅长谱写极具表现力、情感激荡澎湃的音乐。"),
        SubtitleItem(timeMinute=5, timeSecond=38.03, text="注意乐团每个简短的乐句如何被钢琴越来越“半音化”（使用作品主调之外的多彩音符）的回应所接应，之后逐渐溶解一段柔和的新旋律。"),
        SubtitleItem(timeMinute=6, timeSecond=20.22, text="聆听圆号持续奏出轻柔的长音。这被称为“踏板音”，类似于管风琴手用脚在踏板上保持的长音。"),
        SubtitleItem(timeMinute=6, timeSecond=38.18, text="钢琴部分轻松自如地过渡到乐章的抒情第二主题，在极简伴奏下演奏，之后将其传递给弦乐部分。"),
        SubtitleItem(timeMinute=7, timeSecond=27.15, text="独奏钢琴以四个赞美诗般的和弦进入，这是对前一主题简化并放慢的变奏。"),
        SubtitleItem(timeMinute=7, timeSecond=54.04, text="注意听，音乐逐渐显得更具驱动力。弦乐和圆号的“短一长”重复模式以及钢琴的飞速音阶进一步增强了这种效果。"),
        SubtitleItem(timeMinute=8, timeSecond=8.13, text="在键盘上广泛游走后，钢琴聚焦于一个长而高的颤音（快速交替演奏两个音符），随后向上移动，最终又下坠融入一段完整的乐团乐段。"),
        SubtitleItem(timeMinute=8, timeSecond=50.02, text="注意听节奏能量的突然变化，以及现在落在每小节第二拍上的“突强”重音。"),
        SubtitleItem(timeMinute=9, timeSecond=12.09, text="钢琴轰鸣着进入，连续演奏三个上升音阶，最后是一个号角齐奏般的动机。乐团回应时，暗示了一种疑虑，情绪也随之转变。"),
        SubtitleItem(timeMinute=9, timeSecond=31.08, text="在这一部分，钢琴家的右手以八度演奏主旋律，左手紧随其后。独奏旋律线流畅滑行，而 乐团围绕着它创造出饶有趣味的节奏。"),
        SubtitleItem(timeMinute=9, timeSecond=44.04, text="木管组与钢琴之间有一段简短的对话，各自重复其陈述，随后钢琴音符变得如闪电般迅捷，轻盈地在键盘上上下穿梭。"),
        SubtitleItem(timeMinute=10, timeSecond=58.28, text="乐团以全力齐奏重复不祥的主部主题，回应钢琴活泼、迅捷的经过段。这种热烈的能量很快消散，钢琴带出了更为柔和的情绪。"),
        SubtitleItem(timeMinute=11, timeSecond=37.20, text="或许你能听出钢琴奏出相同的极快音符（每拍四个音），而木管和弦乐则演奏两条对比鲜明的较慢旋律。"),
        SubtitleItem(timeMinute=11, timeSecond=54.24, text="钢琴与乐团刚刚分享了乐章如歌的第二主题；随后，钢琴进行了片刻独奏，哀怨的双簧管和巴松管给出回应。"),
        SubtitleItem(timeMinute=12, timeSecond=38.21, text="现在，钢琴展开了一段更长的独奏。弦乐提谨慎地伴奏，主要使用单和弦，帮助强化每小节的主拍。"),
        SubtitleItem(timeMinute=13, timeSecond=1.26, text="独奏家的左手手指变得更加活跃，上下奔跑，而右手在高音区演奏装饰音；随后，两只手再次以八度结合，向前推进。"),
        SubtitleItem(timeMinute=13, timeSecond=33.08, text="钢琴再次奏响一个长而高的颤音，同时圆号和小号演奏坚实的主旋律，推动乐团进入一阵狂热，随后突然停止。"),
        SubtitleItem(timeMinute=14, timeSecond=12.16, text="钢琴开始了一段华彩乐段，在这种篇幅较长、形式自由的无伴奏乐段里，独奏者得以充分展示其技巧。华彩乐段通常是即兴的，但贝多芬为这段华彩谱写了完整的音乐。"),
        SubtitleItem(timeMinute=14, timeSecond=36.22, text="典型的华彩乐段会融入并发展已出现过的素材和主题。在这里，贝多芬以多个主题为基础，进发出狂野的音符洪流。"),
        SubtitleItem(timeMinute=15, timeSecond=1.14, text="在使用“两个长和弦后接快速短音”的模式四次后，贝多芬将这一乐思带入了他悸动想象的深处。"),
        SubtitleItem(timeMinute=15, timeSecond=31.15, text="这里近乎直接引用了乐章早前部分，其简洁与我们刚刚耳闻的狂热形成了鲜明对比。"),
        SubtitleItem(timeMinute=15, timeSecond=59.24, text="贝多芬瞬间改变了情绪：与华彩乐段通常的写法不同，这里的音乐标记为“急板”（非常快），释放出一个全新的乐思。"),
        SubtitleItem(timeMinute=16, timeSecond=30.16, text="正如他之前所做的那样，贝多芬让钢琴的右手奏出一个长颤音，但现在左手也随之加入，演奏与右手非常接近的音。"),
        SubtitleItem(timeMinute=16, timeSecond=57.11, text="又出现了一串颤音。这些颤音以几乎难以察觉的变化，向乐团发出了华彩乐段即将结束的信号。"),
        SubtitleItem(timeMinute=17, timeSecond=9.02, text="沉寂的乐团幽灵般地回归。定音鼓将一个安静而不祥的音型重复四次，助推乐团的张力迅速攀升。"),
        SubtitleItem(timeMinute=17, timeSecond=50.26, text="在最后的华丽段落中，整个乐团轰鸣，钢琴疾驰而下，随后再次窜升；整个乐团以节奏一致的四个清脆和弦结束。"),
        SubtitleItem(timeMinute=18, timeSecond=11.25, text="    "),
        # ----- 第二乐章 -----
        SubtitleItem(timeMinute=18, timeSecond=17.02, text="开篇的脆弱宁静与第一乐章的激荡情感形成鲜明对比。乐团沉默，仿佛时间被暂停。"),
        SubtitleItem(timeMinute=18, timeSecond=40.21, text="贝多芬将音乐设置在远离第一乐章的调性中，借此强调氛围的惊人转变。"),
        SubtitleItem(timeMinute=18, timeSecond=59.18, text="注意听，贝多芬在这里通过寥寥三个音创造的神奇变化。音乐现在感觉更扎实，但随着钢琴抒情旋律的展开，它又变得更恳切。"),
        SubtitleItem(timeMinute=19, timeSecond=21.16, text="乐团的进入没有落在主拍上，而是在两个主拍之间的“切分”上开始，因而显得更加迷人。"),
        SubtitleItem(timeMinute=19, timeSecond=48.21, text="小提琴和中提琴钟表般精准地演奏，而第二巴松管、大提琴和低音提琴则奏响真挚的下行旋律，为小提琴注入新的能量。"),
        SubtitleItem(timeMinute=20, timeSecond=29.05, text="在这段钢琴独奏中，钢琴家在每小节的每一拍上都演奏了多个音；与此同时，乐团在背景中进行伴奏。"),
        SubtitleItem(timeMinute=20, timeSecond=53.24, text="钢琴家的两只手在这里以八度演奏，这要求演奏者具备极高的精确度，以确保旋律清晰而又不显得机械或僵硬。"),
        SubtitleItem(timeMinute=21, timeSecond=12.70, text="现在，钢琴与乐团在本乐章中首次展开对话。乐团更华丽的段落似乎激发了钢琴的更高技巧。"),
        SubtitleItem(timeMinute=21, timeSecond=51.01, text="虽然钢琴部分在这里异常忙碌，在键盘上演奏琶音（类似竖琴式的分解和弦），但也别忘了听独奏长笛与巴松管之间令人难忘的对话。"),
        SubtitleItem(timeMinute=22, timeSecond=22.21, text="长笛与巴松管二重奏的性格在此改变：我们刚刚听到的轻柔下行音符被更为坚决的乐句取代，两者相互穿插。"),
        SubtitleItem(timeMinute=22, timeSecond=42.28, text="长笛与巴松管逐渐消匿，钢琴闪烁下行，回到开篇主题，但只持续了片刻。乐团突然插入，将对话带入新的方向。"),
        SubtitleItem(timeMinute=23, timeSecond=29.14, text="尽管开始时或许难以辨明，但这段钢琴旋律其实是早期主题的装饰版本。贝多芬通过添加装饰音对其进行了变化。"),
        SubtitleItem(timeMinute=23, timeSecond=53.04, text="神奇的转变再次出现。起初，钢琴的重复音（自然音 B）是和声的核心；随后它作为支点，引出令人着迷的变调。"),
        SubtitleItem(timeMinute=24, timeSecond=16.03, text="注意听，中提琴和大提琴是如何在狭窄的音域内快速而流畅地演奏的。它们创造出类似低语的效果，为乐团其余部分提供支撑。"),
        SubtitleItem(timeMinute=25, timeSecond=05.23, text="这段钢琴独奏富有张力而又克制：相同的上升模式不加变化地重复了四次，而乐团的和声则围绕着它发生变化。"),
        SubtitleItem(timeMinute=25, timeSecond=27.27, text="最终，钢琴向前推进，释放出一连串沸腾的音符。钢琴右手的一串啁啾声，或许能让你联想到鸟呜。"),
        SubtitleItem(timeMinute=25, timeSecond=39.16, text="我们进入了另一个华彩乐段，这是钢琴家展示其创造力的机会。这段华彩热情奔放且富于表现力，与乐章的沉思情绪相辅相成。"),
        SubtitleItem(timeMinute=26, timeSecond=19.21, text="在钢琴华彩乐段犹豫不决的结尾之后，乐团轻柔地重复了乐章开篇主题，给人以安心之感。"),
        SubtitleItem(timeMinute=26, timeSecond=38.09, text="钢琴奏响最后一丝惆怅的旋律，随后与长笛和圆号一同下行。但最后，贝多芬以一声响亮的和弦颠覆了我们的期待，如同突然的呼喊。"),
        # ----- 第三乐章 -----
        SubtitleItem(timeMinute=27, timeSecond=9.20, text="这个乐章是一首回旋曲，意味着钢琴和乐团的亢奋旋律将多次回归——有时完全相同，有时略有变化。"),
        SubtitleItem(timeMinute=27, timeSecond=30.00, text="钢琴的脉搏放缓，像需要上发条的钟表，但它随机又突然再次前冲，重申回旋曲主题的结尾。"),
        SubtitleItem(timeMinute=28, timeSecond=11.16, text="铜管和低音木管开始了一段阴沉的齐奏，钢琴则以一连串向上的装饰音回应。铜管和木管再次响起，激起了钢琴的活力。"),
        SubtitleItem(timeMinute=28, timeSecond=39.20, text="乐团以极为简单的乐思伴奏这段相当活泼的钢琴乐段——通常只是用单和弦来标记每小节的强拍。"),
        SubtitleItem(timeMinute=29, timeSecond=58.28, text="弦乐在这里奏响了一个无忧无虑的主题，但钢琴很快带着快速的三连音（每拍三个音符）回归，螺旋上升，随后又沿着键盘的白键和黑键翻滚而下。"),
        SubtitleItem(timeMinute=29, timeSecond=24.20, text="在前一段独奏结尾处，你是否听到钢琴急忙跳回了回旋曲主题？与此同时，弦乐以拨奏（或拨弦）方式进行伴奏。"),
        SubtitleItem(timeMinute=29, timeSecond=50.27, text="乐团暂停，为另一段独奏华彩乐段让路。不过这段华彩乐段非常短，而且不同于大量即兴的协奏曲华彩，贝多芬明确指定了要演奏的音。"),
        SubtitleItem(timeMinute=30, timeSecond=9.26, text="聆听第一双簧管如何将旋律从小调推向大调。这一变化持续片刻，随后乐团果断地回归小调。"),
        SubtitleItem(timeMinute=30, timeSecond=32.23, text="音色甜美的单簧管现在以柔和、舒缓的旋律将我们带入截然不同的情绪。钢琴随后接过旋律并进一步发展。"),
        SubtitleItem(timeMinute=30, timeSecond=42.29, text="钢琴展开了一段对新主题的炫技变奏，随后单簧管和巴松管重新进入，演奏同一主题的朴素结尾。"),
        SubtitleItem(timeMinute=31, timeSecond=29.28, text='情绪再次转变。现在我们听到大提琴奏响了回旋曲主题的一个版本，用于开启一段迷你"赋格"，不同乐器在其中轮流演奏相同的旋律构思。'),
        SubtitleItem(timeMinute=31, timeSecond=55.10, text='突然，乐团放弃了赋格游戏，统一演奏相同的钟表般的重复音。钢琴模仿这一乐思，随后又开始一段回旋曲主题的新变奏。'),
        SubtitleItem(timeMinute=32, timeSecond=18.18, text='小提琴再次奏响钟表动机，而其他乐器反复演奏回旋曲主题的前三个音。紧张情绪逐渐累积，直到⋯'),
        SubtitleItem(timeMinute=32, timeSecond=43.23, text='回旋曲主题完整回归，首先是钢琴，随后是乐团。注意听忙碌的低音乐器（巴松管、大提琴和低音提琴）在主题下轰鸣。'),
        SubtitleItem(timeMinute=33, timeSecond=4.23, text='更多的管乐加入齐奏，钢琴以华丽的回应作答。尽管这段主题开始时完全重复了其首次出现，但钢琴部分很快转向不同的调性。'),
        SubtitleItem(timeMinute=33, timeSecond=33.01, text='钢琴右手的俏皮跳跃被一些人比作驴叫，为结尾段落带来了幽默与轻松感，在这部大体上很严肃的协奏曲中提供了片刻怡人的喘息机会。'),
        SubtitleItem(timeMinute=34, timeSecond=4.02, text='这段钢琴听起来像回旋曲主题，但我们很快意识到它并不相同。或许贝多芬在为我们准备什么。'),
        SubtitleItem(timeMinute=34, timeSecond=37.0, text='答案揭晓：是另一段短华彩。似乎地面在我们脚下移动；突然，钢琴在新的节奏模式下高速启动。'),
        SubtitleItem(timeMinute=34, timeSecond=52.47, text='聆听钢琴的轻快音符如何与长笛、双簧管和圆号的持续长音形成对比，定音鼓的滚奏点缀其间。木管伴奏随后推动音乐继续向前。'),
        SubtitleItem(timeMinute=35, timeSecond=29.12, text='乐团以活力四射的切分节奏开始了最后的冲刺。乐团与独奏者昂首阔步，冲向最后的重复和弦。'),
        SubtitleItem(timeMinute=35, timeSecond=52.17, text='    '),
    ]

    try:
        write_srt_to_file("./output/贝钢协3+英雄生涯@4020+尼尔森斯+布朗夫曼.srt", demo_subtitles)
    except Exception as e:
        print(f"程序运行出错: {str(e)}")

        